apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  namespace: bernardoforcillo-com
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bernardoforcillo-com
      tier: personal-website
  template:
    metadata:
      labels:
        app: bernardoforcillo-com
        tier: personal-website
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bernardoforcillo-com
          image: bernardoforcillo/bernardoforcillo-com:main
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: '128Mi'
              cpu: '50m'
            requests:
              memory: '64Mi'
              cpu: '10m'
          env:
            - name: GTM_ID
              value: GTM-TCMCZB6B
          tty: true
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
